server:
  port: 8081

spring:
  profiles:
    active: dev
  resource:
    static-locations: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 20971520 # 20M
      max-request-size: 1048576000 # 100M
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

characterencoding:
  encoding: utf-8
  requestEncoding: utf-8
  responseEncoding: utf-8

logging:
  file: auto-ai.log
  level:
    .: debug
    org.spring.framework: debug
    com.sohu.auto: debug
    com.baomidou.mybatis-plus: error

---
spring:
  profiles: dev
  redis:
    cluster:
      nodes:  10.18.36.222:7000,10.18.36.223:7002,10.18.36.224:7004,
        10.18.36.223:7003,10.18.36.224:7005,10.18.36.222:7001
      max-redirects: 10
    password: AutoDBnewRedisByMuchao180814
    timeout: 100s
    jedis:
      pool:
        max-active: 1000
        max-idle: 200
        max-wait: 2s
    database: 0
  datasource:
    auto_dealer:
      url: jdbc:mysql://10.11.165.117:3306/dealer?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&zeroDateTimeBehavior=convertToNull
      username: autodealer
      password: autodealer2015
      driver-class-name: com.mysql.jdbc.Driver
    auto_db:
      url: jdbc:mysql://10.18.55.173:3306/auto_db?zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true&allowMultiQueries=true
      username: auto_db_rw
      password: RA5lg5qOKWKb9y1
      driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      #连接池最大使用连接数量
      max-active: 20
      #连接池最小空闲
      min-idle: 0
      max-wait: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 25200000
      #打开removeAbandoned功能
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true

logging:
  file: auto-ai.log
  level:
    .: info
    org.spring.framework: info
    com.sohu.auto: info

cached:
  expire: 3000
  newexpire: 14400
  urlPatterns:
  - /test
  - /salesRank.*
  - /dealerdata.*
  - /transit.*
  - /rank.*

api:
  appKey: automp
  secret: 7be8564b58cc12d4fdc53a320027f577
  host: api.db.auto.sohuno.com
  port: 8000
  esHost: es.db.auto.sohuno.com
  esPort: 8888

---
spring:
  profiles: prod
  redis:
    cluster:
      nodes: 10.16.78.133:6379,10.16.78.133:6380,10.16.78.134:6379,10.16.78.134:6380,10.16.78.135:6379,10.16.78.135:6380,10.16.78.136:6379,10.16.78.136:6380,10.16.78.137:6379,10.16.78.137:6380,10.16.78.138:6379,10.16.78.138:6380
      max-redirects: 10
    password: AutoDBnewRedisByMuchao180814
    timeout: 100s
    jedis:
      pool:
        max-active: 1000
        max-idle: 200
        max-wait: 2s
    database: 0
  datasource:
    auto_dealer:
      url: jdbc:mysql://10.11.165.117:3306/dealer?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&zeroDateTimeBehavior=convertToNull
      username: autodealer
      password: autodealer2015
      driver-class-name: com.mysql.jdbc.Driver
    auto_db:
      url: jdbc:mysql://usedautodbrw.db2.sohuno.com/auto_db?zeroDateTimeBehavior=convertToNull&amp;allowMultiQueries=true
      username: auto_db
      password: 95GpwJ1uJwvqnvF
      driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 0
      #连接池最大使用连接数量
      max-active: 20
      #连接池最小空闲
      min-idle: 0
      max-wait: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 25200000
      #打开removeAbandoned功能
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true

logging:
  file: auto-ai.log
  level:
    .: info
    org.spring.framework: info
    com.sohu.auto: info
    com.baomidou.mybatis-plus: error

api:
  appKey: automp
  secret: 7be8564b58cc12d4fdc53a320027f577
  host: api.db.auto.sohuno.com
  port: 8000
  esHost: es.db.auto.sohuno.com
  esPort: 8888

cached:
  expire: 3000
  newexpire: 900
  urlPatterns:
  - /salesRank.*
  - /dealerdata.*
  - /transit.*
