euraka:
  instance:
    hostname: client
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8765

spring:
  application:
    name: hello-client

logging:
  level:
    org.springframework: DEBUG